const users = [
  {
    id: 1,
    image: "/leminhhung.png",
    name: "Minh Hưng",
    fullName: "Lê Minh Hưng",
    sub_title: "Ping-Pong",
    university: "Ha Noi University of Industry",
    hometown: "Thọ Xuân - Thanh Hóa",
    link: "https://users-qr-code.netlify.app/users/1",
  },
  {
    id: 2,
    image: "/NguyenKhacNguyen.png",
    name: "Khắc Nguyên",
    fullName: "Nguyễn Khắc Nguyên",
    sub_title: "Nhok",
    university: "Ha Noi University of Industry",
    hometown: "Hoài Đức - Hà Nội",
    link: "https://users-qr-code.netlify.app/users/2",
  },
  {
    id: 3,
    image: "/NguyenPhuongNam.jpg",
    name: "Phương Nam",
    fullName: "Nguyên Phương Nam",
    sub_title: "Æ Barca",
    university: "Ha Noi University of Industry",
    hometown: "Tuy Hòa - Phú Yên",
    link: "https://users-qr-code.netlify.app/users/3",
  },
  {
    id: 4,
    image: "/VuThienLy.jpg",
    name: "Thiên Lý",
    fullName: "Vũ Thiên Lý",
    sub_title: "Tắc kè",
    university: "Ha Noi University of Industry",
    hometown: "Kim Bảng - Hà Nam",
    link: "https://users-qr-code.netlify.app/users/4",
  },
  {
    id: 5,
    image: "/HoangDangDuong.jpg",
    fullName: "Hoàng Đăng Dương",
    name: "Đăng Dương",
    sub_title: "Cules",
    university: "Ha Noi University of Industry",
    hometown: "Lò vôi - Bắc Giang",
    link: "https://users-qr-code.netlify.app/users/5",
  },
  {
    id: 6,
    image: "/LeThiHien.jpg",
    name: "Hiền Lê",
    fullName: "Lê Thị Hiền",
    sub_title: "Shmily",
    university: "Ha Noi University of Industry",
    hometown: "Hoằng Hóa - Thanh Hóa",
    link: "https://users-qr-code.netlify.app/users/6",
  },
];

export { users };
